What is NumPy? NumPy is a Python library that makes it easier to work with arrays and perform mathematical, scientific, and statistical computations efficiently.

Core Component: ndarray

The main feature of NumPy is its powerful ndarray object, which stands for n-dimensional array. An ndarray can store data in multiple dimensions (like a list of lists).

Key Features of NumPy Arrays:

Fixed Size: When you create a NumPy array, its size cannot be changed. If you need a different size, you must create a new array.

Same Data Type: All elements in a NumPy array must be of the same data type (e.g., all integers, all floats). Efficient Operations: NumPy arrays are designed to handle large amounts of data efficiently. Operations on NumPy arrays are often faster than similar operations on Python lists because they are implemented in optimized, compiled code. Why Use NumPy?

Performance: NumPy is much faster than Python lists for large datasets. Less Code: It often requires fewer lines of code to perform complex operations with NumPy. Integration: Many scientific and mathematical Python packages (like SciPy, Pandas, and Matplotlib) use NumPy arrays, so knowing NumPy is crucial for working with these tools. Common Uses:

Mathematical Operations: Easily perform calculations like addition, subtraction, multiplication, and division on arrays.

Logical Operations: Compare arrays and perform logical operations.

Shape Manipulation: Reshape, flatten, and transpose arrays.

Sorting and Selecting: Sort data and select elements based on conditions.

Input/Output: Read from and write to files.

Fourier Transforms: Perform discrete Fourier transforms.

Linear Algebra: Solve linear equations and perform matrix operations.

Statistics: Compute mean, median, standard deviation, etc.

Random Simulations: Generate random numbers and simulate data.

                     Why Learn NumPy?
Widespread Use: It’s used in many scientific and mathematical Python libraries.

Efficiency: Makes it easier and faster to work with large datasets.

Foundation for Further Learning: Essential for learning more advanced tools and libraries in the Python ecosystem.

In [2]:
!pip install numpy

In [ ]:
#How to create a basic array,  using zeros Function
import numpy as np
#The default data type for the array is float64, 
#which represents numbers as floating-point values. The decimal point indicates that these are floats.
np.zeros(20)

In [ ]:
#We can change the default data type to int
import numpy as np

# Create an array of 20 zeros with integer data type
array_of_zeros_int = np.zeros(10, dtype=int)

print(array_of_zeros_int)


In [ ]:
#How to create a basic array,  using ones Function
x = np.ones(2)
print(x)

#change dtype to int
y = np.ones(4, dtype=int)
print(y)

In [1]:
import numpy
arr0=numpy.array(2)
arr = numpy.array([1, 2, 3, 4, 5])
print(arr0)
print(arr)
print(arr[:3])

2
[1 2 3 4 5]
[1 2 3]


In [4]:
#numpy using alias
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [5]:
#Checking numpy version
import numpy as np
print(np.__version__)

1.24.3


# Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called ndarray.
We can create a NumPy ndarray object by using the array() function.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr2=np.array(50)
print("arr details:")
print(arr)
print(type(arr))
print(arr.ndim)

print("arr2 details:")
print(arr2)
print(type(arr2))
print(arr2.ndim)

arr details:
[1 2 3 4 5]
<class 'numpy.ndarray'>
1
arr2 details:
50
<class 'numpy.ndarray'>
0


In [ ]:
Dimensions in Arrays/Nested Arrays
A dimension in arrays is one level of array depth (nested arrays).

In [1]:
import numpy as np
# Single Dimention 1D Array creation
rollNo = [11, 22, 33, 44]
a1D = np.array(rollNo)

# Double Dimention 2D Array creation

rollNo2D = [
    [1, 2], [3, 4]
    ]
a2D = np.array(rollNo2D)

# Three Dimention 3D Array creation
rollNo3D = [
    [
        [1, 2], [3, 4]], [[5, 6], [7, 8]
    ]
]
a3D = np.array(rollNo3D)

#Print 1D Array
print(rollNo)
#Print 2D Array
print(rollNo2D)
#Print 3D Array
print(rollNo3D)

[11, 22, 33, 44]
[[1, 2], [3, 4]]
[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]


In [6]:
# 0-D Dimension Array
import numpy as np
arr = np.array(42)
print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


In [1]:
#Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [2]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
new_arr=np.array([[1,3,4],[10,20,30]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [7]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [3]:
#Check how many dimensions the arrays have:

import numpy as np
a=np.array([1,2,3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]],[[1,1,1],[2,2,2]]])
e=np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(a.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(e)

1
2
3
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
#Specifying dimension while creating the array
import numpy as np
arr = np.array(42, ndmin=2)

print(arr)
print('number of dimensions :', arr.ndim)

[[42]]
number of dimensions : 2


In [ ]:
import numpy as np
x=[10,20,30,40]
arr = np.array((1, 2, 3, 4, 5))
arr2=np.array(x,ndmin=2)
print(arr)
print(arr2)

In [24]:
#Indexing in arrays
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[1:])

[2 3 4]


In [25]:
#Get third and fourth elements from the following array and add them.
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [6]:
#Access 2-D Arrays
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,12]])
print('2nd element on 1st row: ', arr[1,2])

2nd element on 1st row:  8


In [1]:
#Access 3-D Arrays
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [5]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])
print(arr[0:2, 0:2, 2])
print(arr[0:2,1,0:2])

6
[[ 3  6]
 [ 9 12]]
[[ 4  5]
 [10 11]]


In [12]:
#From both elements, return index 2:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [41]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [4]:
#Get the shape of array
import numpy as np
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr2 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],[[11, 12, 13, 14], [15, 16, 17, 18]]])
print(arr1.ndim)
print(arr1.shape)
print()
print(arr2.shape)

2
(2, 4)

(2, 2, 4)


In [5]:
#Reshape From 1-D to 3-D
#Example : Convert the following 1-D array with 12 elements into a 3-D array.
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr1 = arr.reshape(4, 3)
newarr2 = arr.reshape(3, 4)
newarr3 = arr.reshape(2,2,3)
print(arr.ndim)
print(newarr1.ndim)
print(newarr1)
print()
print(newarr2)
print()
print(newarr3)
print()
newarr4 = arr.reshape(2, 3, 2)
print(newarr4)

1
2
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 2)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,2)

# Iterating Arrays

In [61]:
import numpy as np

arr = np.array([1, 2, 3])
for x in arr:
    print(x)

1
2
3


dfyhjijoko

In [62]:
#Iterating 2-D Arrays
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [8]:
#Iterate on each scalar element of the 2-D array:

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y, end=" ")
    print()
    

1 2 3 
4 5 6 


In [66]:
#Iterating 3-D Arrays
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z, end=" ")
        print()

1 2 3 
4 5 6 
7 8 9 
10 11 12 


In [5]:
#Iterating Arrays Using nditer()
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x, end=" ")

1 2 3 4 5 6 7 8 

In [9]:
#Join two arrays

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6, 9])
arr = np.concatenate((arr1, arr2))
print(arr)
print(arr.ndim)

[1 2 3 4 5 6 9]
1


In [1]:
#NumPy provides a helper function: vstack()  to stack along columns.
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
#arr3=np.array([7,8,9])
arr = np.vstack((arr1, arr2))
print(arr1.ndim)
print(arr)
print(arr.ndim)

1
[[1 2 3]
 [4 5 6]]
2


In [5]:
#NumPy provides a helper function: vstack()  to stack along columns.
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
#arr3=np.array([7,8,9])
arr = np.hstack((arr1, arr2))
arr3=np.concatenate((arr1,arr2))
print(arr1.ndim)
print(arr)
print(arr.ndim)
print(arr3)

1
[1 2 3 4 5 6]
1
[1 2 3 4 5 6]


In [20]:
#Split the array in 3 parts:

import numpy as np
arr = np.array([1, 2, 3, 4,5,6])
#arr = np.array([1, 2, 3, 4,5])
#arr = np.array([1, 2, 3, 4,5,6,7])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [84]:
#Split the array in 4 parts:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 6, 5])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6]), array([6, 5])]


In [1]:
#Find the indexes where the value is 4:

import numpy as np
arr = np.array([4, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([0, 3, 5, 6], dtype=int64),)


In [21]:
#Find the indexes where the values are even:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [23]:
#Find the indexes where the values are odd:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 !=0)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [9]:
#COPY:Make a copy of an array, change the original array, and display both arrays:

import numpy as np

arr = np.array([10, 2, 3, 4, 5])
x = arr.copy()
print(arr)
print(x)

arr[2] = 42
x[3]=90

print(arr)
print(x)

[10  2  3  4  5]
[10  2  3  4  5]
[10  2 42  4  5]
[10  2  3 90  5]


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
print(arr)
print(x)
#making changes in arr
arr[0] = 42
print(arr)
print(x)
print()
#Making changes in view
x[0] = 31
print(arr
     )
print(x)


[1 2 3 4 5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]

[31  2  3  4  5]
[31  2  3  4  5]


In [6]:
'''Check if the array owns the data.
copies owns the data, and views does not own the data.

Every NumPy array has the attribute base that returns None if the array owns the data.
Otherwise, the base  attribute refers to the original object.

Print the value of the base attribute to check if an array owns it's data or not:
'''
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [6]:
#Sorting Arrays
#Sorting means putting elements in an ordered sequence

import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
sorted_array=np.sort(arr)
rev_array=sorted_array[::-1]
print(sorted_array)
print(rev_array)

[0 1 2 3]
[0 1 2 3]
[3 2 1 0]


In [87]:
#Sort the array alphabetically:

import numpy as np
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [88]:
#Sort a boolean array:

import numpy as np
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [89]:
#Sort a 2-D array:

import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# NumPy arange(): How to Use np.arange()

NumPy arange() is one of the array creation routines based on numerical ranges. It creates an instance of ndarray with evenly spaced values and returns the reference to it.

You can define the interval of the values contained in an array, space between them, and their type with four parameters of arange():

numpy.arange([start, ]stop, [step, ], dtype=None) -> numpy.ndarray

In [ ]:
The first three parameters determine the range of the values, while the fourth specifies 
the type of the elements:

start is the number (integer or decimal) that defines the first value in the array.
stop is the number that defines the end of the array and isn’t included in the array.
step is the number that defines the spacing (difference) between each two consecutive values
in the array and defaults to 1.
dtype is the type of the elements of the output array and defaults to None.
step can’t be zero. Otherwise, you’ll get a ZeroDivisionError. 
You can’t move away anywhere from start if the 
increment or decrement is 0.

In [5]:
import numpy as np
x=np.arange(start=1, stop=10, step=2)
print(x)

[1 3 5 7 9]


In [4]:
import numpy as np
np.arange(1, 10.1, 3)

array([ 1.,  4.,  7., 10.])

In [98]:
#Providing Negative Arguments
import numpy as np
np.arange(-5, -1, 2)

array([-5, -3])

In [10]:
#Counting Backwards
import numpy as np
np.arange(5, 1, -1)
#print(x)

array([5, 4, 3, 2])

# Some Logical operations

In [2]:
#Some logical Operation
#print all the numbers greater than 5
data = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(data[data>=5])

[ 5  6  7  8  9 10 11 12]


In [ ]:
#You can select elements that are divisible by 2:
data = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
divisible_by_2 = data[data%2!=0]
print(divisible_by_2)


In [ ]:
#you can select elements that satisfy two conditions using the & and | operators:
data = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
c = data[(data > 2) & (data < 11)]
print(c)

In [ ]:
#You can create a new array from a section of your array 
#any time by specifying where you want to slice your array.
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

arr1 = a[3:8]
arr1

In [ ]:
#You can add the arrays together with the plus sign.

data = np.array([1, 2])
print(data)
ones = np.ones(2, dtype=int)
print(ones)
newdata = data + ones
print("-----")
print(newdata)

In [ ]:
#You can, of course, do more than just addition!
data = np.array([1, 2])
print(data)
ones = np.ones(2, dtype=int)
minus = data - ones
print(minus)

multi = data * data
print(multi)

div = data / data
print(div)



In [ ]:
#To add the rows or the columns in a 2D array, you would specify the axis.

#If you start with this array:

b = np.array([[1, 1], [2, 2]])

#You can sum over the axis of rows with:

ans = b.sum(axis=0)
print(ans)


#You can sum over the axis of columns with:

ans1 = b.sum(axis=1)
print(ans1)



In [ ]:
#More useful array operations
#data = np.array([11,22,33,55,44,33,66,88,77])
data = np.array([[1, 1], [2, 2]])
max = data.max()
print(max)

min = data.min()
print(min)

sum = data.sum()
print(sum)


In [ ]:
#How to get unique items and counts
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

In [ ]:
#To get the indices of unique values in a NumPy array
#(an array of first index positions of unique values in the array), 
#just pass the return_index argument in np.unique() as well as your array.
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)
print(unique_values)

In [ ]:
#You can pass the return_counts argument in np.unique() along with your array to get 
#the frequency count of unique values in a NumPy array.
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

In [ ]:
#This also works with 2D arrays! If you start with this array:

a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

#You can find unique values with:

unique_values = np.unique(a_2d)
print(unique_values)


In [ ]:
#Reversing a 1D array

#If you begin with a 1D array like this one:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

#You can reverse it with:

reversed_arr = np.flip(arr)

#If you want to print your reversed array, you can run:

print('Reversed Array: ', reversed_arr)


In [ ]:
#Reversing a 2D array

#A 2D array works much the same way.

#If you start with this array:

arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

#ou can reverse the content in all of the rows and all of the columns with:

reversed_arr = np.flip(arr_2d)
print(reversed_arr)

#You can easily reverse only the rows with:

reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

#Or reverse only the columns with:

reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

#You can also reverse the contents of only one column or row. 
#For example, you can reverse the contents of the row at index position 1 (the second row):

arr_2d[1] = np.flip(arr_2d[1])

#You can also reverse the column at index position 1 (the second column):

arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)


# Case Study:The Nagpur West Side CEO collects data on the monthly incomes (in Indian Rupees) of a sample of 12 potential customers in Nagpur:



In [ ]:
import numpy as np

# Given data
incomes = np.array([30000, 25000, 35000, 40000, 30000, 28000, 22000, 32000, 38000, 30000, 26000, 34000])

# Calculate Mean
mean_income = np.mean(incomes)
print("Mean Income:", mean_income)

# Calculate Median
median_income = np.median(incomes)
print("Median Income:", median_income)

# Calculate Mode (Using NumPy)
(unique, counts) = np.unique(incomes, return_counts=True)
mode_income = unique[np.argmax(counts)]
print("Mode Income:", mode_income)


Based on the calculations of mean, median, and mode from the given dataset of 
monthly incomes of potential customers in Nagpur, we can draw the following conclusions:

Mean Income:

Value: ₹30833.3
Interpretation: The average monthly income of the sample of 10 potential 
customers is ₹30833.3. This value provides an overall sense of the purchasing power of the residents in the sample. 
However, it can be influenced by extreme values (outliers).
Median Income:

Value: ₹30000.0
Interpretation: The median monthly income is ₹30,000, which means that half 
of the residents in the sample earn more than ₹30,000, and the other half earn less. The median is less affected by outliers and gives a better sense of the typical income in the sample.
Mode Income:

Value: ₹30000
Interpretation: The mode is ₹30000, indicating that this income value 
occurs most frequently in the sample. It shows the most common income level among the potential customers.

Inferences
Purchasing Power:

The mean and median incomes suggest that the average resident in the 
sample has a moderate level of purchasing power. The median being close to the mean indicates a relatively symmetrical distribution of incomes.

Income Distribution:

The mode, which is the same as the median in this case, 
confirms that ₹30,000 is the most common income among the sampled residents. This uniformity suggests that a significant portion of the population has similar earning levels.
Business Viability:

The consistent values of mean, median, and mode around ₹30,000 suggest 
a stable income distribution among potential customers. This consistency can be a positive indicator for the CEO considering opening a West Side Store in Nagpur. A relatively homogenous income distribution implies predictable spending patterns, which can aid in business planning and marketing strategies.

Further Considerations:

While the sample provides useful insights, it is important to consider a 
larger and more diverse sample to get a comprehensive understanding of the 
city's overall purchasing power. Additionally, other factors such as cost of living, 
competition, and consumer behavior should also be evaluated before making a final decision.

# Finding Std.Deviation and Variance using numpy

In [126]:
#Find Standard Deviation
import numpy as np
x = np.arange(159)
print(np.std(x))

45.89843860815601


In [127]:
#Find Variance
import numpy as np
x = np.arange(159)
print(np.var(x))

2106.6666666666665
