# Numpy-array Libraries

In [ ]:
!pip install numpy

In [5]:
import numpy as np
array1 = np.array([10,20,30,40,50])
print(array1)

[10 20 30 40 50]


In [7]:
import numpy as np
a1 = np.array([10,15,12])
print(a1)

[10 15 12]


In [8]:
import numpy as np
print(np.__version__)

2.2.1


In [ ]:
!pip install --upgrade numpy

In [1]:
import numpy as np
# using zeros function
np.zeros(20)
# which reprensents numbers as floating point values the decimal point indicates that these are floats 
# default data type for the array is float64

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [2]:
import numpy as np
# create an array of 20 zeroes with interger data type
# change default data type to int
array_of_zeroes_int = np.zeros(20,dtype=int)
print(array_of_zeroes_int)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [3]:
#  how to create a basic array using ones function 
x = np.ones(2)
print(x)
# change dtype to int
y = np.ones(4, dtype=int)
print(y)

[1. 1.]
[1 1 1 1]


In [4]:
import numpy
arr0 = numpy.array(2)
arr = numpy.array([1,2,3,4,5])
print(arr0)
print(arr)
print(arr[:3])

2
[1 2 3 4 5]
[1 2 3]


In [5]:
# numpy using alias
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


# numpy Ndarray object
# number of dimensions(.ndim) 0 1 2 3 

In [6]:
import numpy as np
arr1 = np.array(50)
print("arr details :")
print(arr1)
print(type(arr1))
print(arr1.ndim)

arr2 = np.array([1,2,3,4,5])
print(arr2)
print(type(arr2))
print(arr2.ndim)

arr details :
50
<class 'numpy.ndarray'>
0
[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [1]:
import numpy as np
# Single Dimention 1D Array creation
rollNo = [11, 22, 33, 44]
a1D = np.array(rollNo)

# Double Dimention 2D Array creation

rollNo2D = [[1, 2], [3, 4]]
a2D = np.array(rollNo2D)

# Three Dimention 3D Array creation
rollNo3D = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
a3D = np.array(rollNo3D)

#Print 1D Array
print(a1D)
#Print 2D Array
print(a2D)
#Print 3D Array
print(a3D)

[11 22 33 44]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [2]:
# 0-D Dimension Array
import numpy as np
arr = np.array(42)
print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


In [4]:
import numpy as np
arr = np.array([3,2,0,1])
sorted_array = np.sort(arr)
rev_array = sorted_array[::-1]
print(sorted_array)
print(rev_array)

[0 1 2 3]
[3 2 1 0]


In [ ]:
import numpy as np
